### ISSUE TITLE
Crashes on win8.1 straight away

### ISSUE THREAD

**Issue by shMatrix** [saynotosync/Matrix-PON-Framerate-Fix#3]
Original ThirteenAG/WidescreenFixes script works without any problrms.

**Comment by adc-ax** [comment]
Likely the same as issue #2 

https://github.com/saynotosync/Matrix-PON-Framerate-Fix/issues/2

Will investigate and hopefully fix them both over Thanksgiving weekend.

**Comment by adc-ax** [comment]
@shMatrix could you please tell me the exact size of your "Matrix3W32S.bin" file? I want to check whether I have a different version of the game (with a differently compiled binary, which would be kind of weird, but I don't think it'd hurt to check).

**Comment by adc-ax** [comment]
This issue seems to be endemic to the 1.2 cracked .bin from Deviance group (23,052,288 bytes in size) specifically, as that was the only binary that presented me with it.

**Comment by adc-ax** [comment]
Fixed in the latest version of the script.
